### ISSUE TITLE
ACS data source?

### ISSUE THREAD

**Issue by tchang1997** [epierson9/disease-testing-thresholds#1]
Hi, 

Thank you for making this resource available! I was trying to re-run the analysis in `analysis.ipynb`, but I'm not sure where I can download the data.

I was able to get some Indiana data via Wayback, but I wondering if I could get more information about how I can get/correctly preprocess the ACS data used in this study -- specifically `acs_2018_5_year_census_data_zipcode.csv` and `acs_2018_5_year_census_data_county.csv`.

**Comment by epierson9** [comment]
The files are now added!
